### ISSUE TITLE
add propertyname operator from jsonpath-plus

### ISSUE THREAD

**Issue by JefeDavis** [vmware-labs/yaml-jsonpath#44]
from https://jsonpath.com

given the document
```json
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

and the query 
```
$.firstName~
```
the output would be 
```
firstName
```

unfortunately this does not seem to be implemented in this library

this appears to come from the jsonpath-plus implementation located here: https://jsonpath-plus.github.io/JSONPath/docs/ts/

this would be useful as there is no way currently to get the yaml node containing the property name today

**Comment by glyn** [comment]
A few comments:
1. It would be helpful to describe what use this feature is in practice, i.e. when is it useful to obtain property keys?

2. `Find` returns `[]*yaml.Node` which in this case will be an array of pointers to key nodes. These keys are part of a map from key to value. It is not clear that modifying a key will be well defined since the hash value of the key will probably be modified too and the underlying map may be rendered unusable.

3. Note that jsonpath-plus seems to allow `~` to return array indices as well as object keys. It seems the intention here is to omit this in which case it would be good to add a testcase to ensure the correct syntax error is returned when an attempt it made to return array indices.

4. I'm wondering  what is supposed to happen if`[*]~` is applied to an array.

**Comment by ahuffman** [comment]
@glyn for item 1, we're leveraging this library in a go program to manipulate/patch yaml files.  One of the features we'd like to add is a means for an end-user to modify an existing key (property in JSONPath lingo).  This is extremely useful in a Kubernetes yaml manifest context where the end-user may not be in control of the original manifest, but would like to use it as a starting point towards a final configuration.  

Typically there will be times when an admission controller running on a Kubernetes cluster has a policy to only allow Kubernetes objects to get created when they meet certain {.metadata.labels} requirements.  Many upstream Kubernetes manifests provide labels that may or may not meet the standards of the admission control policy.  

As an example a common metadata.label is `name`, but Kubernetes documentation on labeling best-practices is to use the `app.kubernetes.io/name` label.  

In this case we'd like to be able to retrieve the yaml node for the key by doing a JSONPath query of `{.metadata.label.name~}` which would return us the yamlNode for the key in this case.  We can then update the key with the desired value of `app.kubernetes.io/name`.

**Comment by JefeDavis** [comment]
@glyn in regards to item 2. Im not sure I'm following. yaml.Node represents keys and values as separate nodes in an array underneath a yaml.MappingNode object where the keys have an even index and the values have an odd index. in this case we are just returning the even index for the property name node instead of the odd index for the value node. modifying these yaml nodes would be the same as modifying the value nodes as yaml.Node does not make a distinction between the two, treating both as scalar nodes.

**Comment by glyn** [comment]
@JefeDavis Ah, that makes sense. I was concerned in case there was a hash map or similar associated with the keys and values, but if there isn't, then the only issue is that you could modify the key to be a duplicate of another key in the same object which may cause unexpected behaviour. Might this be worth documenting?

**Comment by JefeDavis** [comment]
@glyn good catch on item 3 i will add it to the pr

as far as item 4 goes if ~ is used in the context of a bracket child it will correctly output all childrens names correctly e.g.
given:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: bind-udp
  namespace: tanzu-dns
  labels:
    app.kubernetes.io/name: external-dns
  annotations:
    # NOTE: this only works on 1.19.1+vmware.1+, but not prior
    ## This annotation will be ignored on other cloud providers
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    test: hello
    app.kubernetes.io/name: external-dns
  type: LoadBalancer
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
```

 and the query
```
spec.ports[0][*]~
```

the result will be:
```yaml
name
---
port
---
protocol
---
targetPort
```
