### ISSUE TITLE
Support for recursive descent with expressions and filter expressions

### ISSUE THREAD

**Issue by rspurgeon** [vmware-labs/yaml-jsonpath#54]
### Describe the bug

Given the following input:
```
plugins:
- config:
    do: rae
    foo: bar
  id: 1
  name: abc
- config:
    do: so
    foo: bar
  id: 2
  name: xyz
services:
- name: my-service
  plugins:
  - config:
      do: rae
      foo: special
    id: 3
    name: abc
- name: my-service
  plugins:
  - config:
      do: false
      foo: bar
    id: 4
    name: rst
```

This selector:
```
$.plugins[?(@.id<2)]
```
returns the expected 
```
name: abc
id: 1
config:
  foo: bar
  do: rae
```

When introducing recursive descent, no results are returned
```
$..plugins[?(@.id<2)]
```

### Reproduction steps

1. Launch the web UI from the library
2. Enter the YAML document from the bug description
3. Paste in the selector "$..plugins[?(@.id<2)]" and click Execute and view no results

<img width="711" alt="Screenshot 2023-07-21 at 10 18 42 AM" src="https://github.com/vmware-labs/yaml-jsonpath/assets/10521262/f4fa2d93-47ef-4186-a837-339c2a325e73">
<img width="763" alt="Screenshot 2023-07-21 at 10 18 51 AM" src="https://github.com/vmware-labs/yaml-jsonpath/assets/10521262/075b13b2-bb31-4d3b-9749-cbb287d28758">

### Expected behavior

Filters should work with recursive descent according to https://goessner.net/articles/JsonPath/

### Additional context

Thank you for this library, any advice on using this library with these features appreciated.
