### ISSUE TITLE
Filter expression on array with combined logical operators

### ISSUE THREAD

**Issue by rspurgeon** [vmware-labs/yaml-jsonpath#60]
### Describe the bug

The library supports existence filtering expressions on arrays with simple values. For example the following is validated in the web application:

input.yaml
```
services:
- host: api.example.com
  routes:
  - methods:
    - POST
    name: create
  - methods:
    - GET
    name: get
  - methods:
    - OPTIONS
    - GET
    name: getopt
```
Expression:
```
$.services[*].routes[?(@.methods[?(@=='GET')])]
```
Returns:
```
methods:
  - GET
name: get
---
methods:
  - OPTIONS
  - GET
name: getopt
```

However, I cannot determine if the inner most expression can be combined with an `&&` or `||` operator to check for the existence of all or any values within an array.

Various expressions have been tried including:
```
$.services[*].routes[?(@.methods[?(@=='GET')] && @.methods[?(@=='OPTIONS')])]
```
Results:
```
Invalid JSON path: invalid path syntax at position 45, following ")]"
```

Is it possible to combine these array existence filters?

### Reproduction steps

1. Start the web application as instructed: https://github.com/vmware-labs/yaml-jsonpath/blob/main/web/README.md
2. Use the input value:
```
services:
- host: api.example.com
  routes:
  - methods:
    - POST
    name: create
  - methods:
    - GET
    name: get
  - methods:
    - OPTIONS
    - GET
    name: getopt
```
3. Use the filter:
```
$.services[*].routes[?(@.methods[?(@=='GET')] || @.methods[?(@=='POST')])]
```
...

### Expected behavior

Combining other filters appears to be supported, so I would expect this filter to return both the array items that contain a `GET` OR a `POST` operation.
